export default () => ({
    database: {
        // type: 'mysql',
        // host: 'lp-hc-rds-db-instance-live.cjiym88ukfdp.ap-south-1.rds.amazonaws.com',
        // port: 3306,
        // username: 'admin',
        // password: '8bX1Y61vCHK1qPVMP6lJ',
        // name: 'lp_high_creation_live',
        // synchronize:true,
        type: 'mysql',
        host: 'localhost',
        port: 3306,
        username: 'root',
        password: 'Tanmay@4321',
        name: 'lp_high_creation_live',
        synchronize: true,
    },
    localDatabase: {
        type: 'postgres',
        host: 'localhost',
        port: 5432,
        username: 'postgres',
        password: 'Tanmay@4321',
        name: 'hci_db',
        synchronize:true,
    },
})